version: "3.7"

services:
  db:
    image: "postgres:latest"
    volumes:
      - ../db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: pgdb
  power-api:
    image: "power-api"
    ports:
      - "3088:3088"
    environment:
      POSTGRES_URL: postgresql://pguser:pgpassword@db:5432/pgdb?schema=public
      S3_KEY: key
      S3_SECRET: secret
      S3_IMAGES_BUCKET: bucket
      JWT_SECRET_ADMIN: jwtadmin
      JWT_SECRET_ADMIN_REFRESH: jwtadminrefresh
