version: "3.7"

networks:
  web:
    driver: bridge
  internal:
    driver: bridge

services:
  # DB
  power-db:
    image: "postgres:latest"
    volumes:
      - ../db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: pgdb
    networks:
      - internal
  # API
  power-api:
    image: "power-api"
    ports:
      - "3088:3088"
    depends_on:
      - power-db
    environment:
      POSTGRES_URL: postgresql://pguser:pgpassword@db:5432/pgdb?schema=public
      S3_KEY: s3key
      S3_SECRET: s3secret
      S3_IMAGES_BUCKET: s3bucket
      JWT_SECRET_ADMIN: jwtsecretadmin
      JWT_SECRET_ADMIN_REFRESH: jwtsecretadminrefresh
    networks:
      - internal
      - web
  # ADMIN
  power-admin:
    image: "power-admin"
    restart: always
    ports:
      - "4000:80"
    networks:
      - web
  # WEB
  power-web:
    image: "power-web"
    restart: always
    ports:
      - "3000:80"
    networks:
      - web
